my-cloud/ruthenium

.github/workflows/codeql-analysis.yml, src/node/encryption/mnemonic.go
Adding default CodeQL Analysis
=> feat(ci): scan code with github ci #36

.github/PULL_REQUEST_TEMPLATE/release.md, .github/pull_request_template.md, .github/workflows/docker-publish.yml, CONTRIBUTING.md, Dockerfile
=> 94 change release process

.github/PULL_REQUEST_TEMPLATE/release.md, .github/pull_request_template.md, .github/workflows/docker-publish.yml, CONTRIBUTING.md, Dockerfile, src/node/blockchain/block.go, src/node/blockchain/human.go, src/node/blockchain/service.go, src/node/blockchain/transaction.go, src/node/neighborhood/block_response.go, src/node/neighborhood/transaction_request.go, src/node/neighborhood/transaction_response.go, test/node/blockchain/block_test.go, test/node/blockchain/service_test.go
=> Release 1.1.0

.github/workflows/docker-publish.yml, README.md
=> chore(ci): deploy a package on release

CONTRIBUTING.md, README.md
=> chore(documentation): update links

.github/workflows/release.yml
=> chore(ci): automatically deploy a package on release

README.md
=> chore(documentation): add badges

.github/workflows/package.yml
=> chore(ci): patch package signature

src/node/encryption/private_key.go, src/node/encryption/wallet.go, src/node/main.go, src/ui/main.go, test/constants.go, test/node/encryption/address_test.go, test/node/encryption/mnemonic_test.go, test/node/encryption/private_key_test.go, test/node/encryption/public_key_test.go, test/node/encryption/wallet_test.go, test/node/protocol/pool_test.go
=> fix(encryption): generated private key may already exist

src/node/protocol/blockchain.go
=> fix(protocol): timestamp verification is wrong

src/ui/server/transaction/handler.go, test/ui/server/transaction/handler_test.go
=> fix(ui): amount too small is not forbidden

src/ui/README.md, src/ui/server/transaction/handler.go, src/ui/server/wallet/handler.go, test/ui/server/transaction/handler_test.go, test/ui/server/wallet/handler_test.go
=> 145 change created status code

.github/workflows/build.yml, .github/workflows/quality.yml, .github/workflows/security.yml
=> chore(ci): add analysis for release branches

src/ui/README.md, src/ui/server/transaction_request.go, src/ui/templates/index.html, test/ui/server/transaction/handler_test.go
=> feat(ui): simplify transaction request

src/ui/README.md, src/ui/server/wallet/amount/handler.go, src/ui/server/wallet/amount_response.go, src/ui/templates/index.html
=> feat(ui): simplify amount response

src/node/README.md, src/node/network/neighbor.go, src/node/network/p2p/host.go, src/node/network/p2p/neighbor.go, src/ui/README.md, src/ui/main.go, src/ui/server/validation/start/handler.go, src/ui/server/validation/stop/handler.go, src/ui/templates/index.html, test/node/network/networktest/neighbor_mock.go, test/ui/server/validation/start/handler_test.go, test/ui/server/validation/stop/handler_test.go
=> feat: rename mining to validation

.github/workflows/quality.yml
=> chore(ci): add a linter and simplify quality workflow

configtest/settings.json, src/node/network/p2p/client_factory.go, src/node/network/p2p/gp2p/client_factory.go, src/node/network/p2p/neighbor.go, test/node/network/p2p/gp2p/client_factory_test.go, test/node/network/p2p/host_test.go, test/node/network/p2p/p2ptest/client_factory_mock.go, test/node/network/p2p/synchronizer_test.go
=> fix(p2p): neighbor finding timeout causes cluster troubles

src/node/protocol/validation/transactions_pool.go, src/node/protocol/verification/blockchain.go, test/node/protocol/protocoltest/block_factory.go, test/node/protocol/validation/transactions_pool_test.go, test/node/protocol/verification/blockchain_test.go
=> fix(node): transactions can be older than 1 block

src/node/network/last_bocks_request.go, src/node/network/p2p/host.go, src/node/protocol/blockchain.go, src/node/protocol/verification/blockchain.go, test/node/network/p2p/host_test.go, test/node/protocol/protocoltest/blockchain_mock.go, test/node/protocol/verification/blockchain_test.go
=> fix(node): using last blocks corrupts the blockchain

src/node/protocol/verification/blockchain.go
=> fix(node): total amount verification is wrong

src/node/network/block_response.go, src/node/protocol/blockchain.go, src/node/protocol/validation/transactions_pool.go, src/node/protocol/verification/block.go, src/node/protocol/verification/blockchain.go, test/node/protocol/protocoltest/block_factory.go, test/node/protocol/protocoltest/blockchain_mock.go, test/node/protocol/validation/transactions_pool_test.go, test/node/protocol/verification/blockchain_test.go
=> fix(node): registered addresses might become too big

config/settings.json, src/node/config/settings.go, src/node/main.go, src/node/protocol/validation/output.go, src/node/protocol/verification/blockchain.go, src/ui/config/settings.go, src/ui/main.go, src/ui/server/transaction/info/handler.go, src/ui/server/wallet/amount/handler.go, templates/index.html, test/node/protocol/validation/output_test.go, test/node/protocol/verification/blockchain_test.go, test/ui/server/transaction/info/handler_test.go, test/ui/server/wallet/amount/handler_test.go
=> feat: calculate income without iteration

config/settings.json, src/node/README.md, src/node/config/settings.go, src/node/network/blocks_request.go, src/node/network/last_blocks_request.go, src/node/network/neighbor.go, src/node/network/p2p/handler.go, src/node/network/p2p/neighbor.go, src/node/protocol/blockchain.go, src/node/protocol/validation/transactions_pool.go, src/node/protocol/verification/blockchain.go, test/node/network/networktest/neighbor_mock.go, test/node/network/p2p/handler_test.go, test/node/network/p2p/neighbor_test.go, test/node/protocol/protocoltest/blockchain_mock.go, test/node/protocol/validation/transactions_pool_test.go, test/node/protocol/verification/blockchain_test.go
=> fix(node): limit blocks responses

src/node/protocol/utxo.go, src/node/protocol/validation/transactions_pool.go, src/node/protocol/verification/blockchain.go, src/node/protocol/verification/transaction.go, test/node/protocol/validation/transactions_pool_test.go, test/node/protocol/verification/blockchain_test.go
=> fix(node): input public key is not verified against output address

src/node/README.md, src/node/protocol/validation/transactions_pool.go, src/node/protocol/verification/block.go, src/node/protocol/verification/blockchain.go, src/node/protocol/verification/output.go, src/node/protocol/verification/transaction.go, src/node/protocol/verification/utxo.go, src/ui/README.md, src/ui/main.go, src/ui/server/transaction/output/progress.go, src/ui/server/transaction/output/progress/handler.go, src/ui/server/transaction/output/progress_info.go, templates/index.html, test/node/protocol/protocoltest/block.go, test/node/protocol/protocoltest/transaction.go, test/node/protocol/verification/blockchain_test.go, test/node/protocol/verification/utxo_test.go, test/ui/server/transaction/handler_test.go, test/ui/server/transaction/output/progress/handler_test.go
=> feat: rename is registered output field
